[package]
name = "hanasu"
version = "0.1.0"
edition = "2021"

[dependencies]
cpal = "0.15.3"
dirs = "5.0.1"
tokio = { version = "1.40.0", features = ["full"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = 'z'
panic = 'abort'

